### ISSUE TITLE
Feature request: allow to set appVersion

### ISSUE THREAD

**Issue by mkj28** [codefresh-contrib/cfstep-helm#10]
something along the lines
```
if `self.app_version is not None:
  package_var += '--app-version ' + self.app_version + ' '
```
helm added support for it in https://github.com/helm/helm/pull/3196/commits/9e869700c0bbb76ebec94b7b12871d6fe27b59ab

**Comment by jdolitsky** [comment]
@mkj28 This is now in master, new images building: https://hub.docker.com/r/codefresh/cfstep-helm/tags

Use `APP_VERSION` env var to use this

**Comment by mkj28** [comment]
awesome, thanks
