### ISSUE TITLE
Feature request: helmfile support

### ISSUE THREAD

**Issue by mkj28** [codefresh-contrib/cfstep-helm#11]
Helmfile combined with this repo would be quite powerful.

To start would be great to have couple actions like:
`ACTION=helmfile_diff` runs `helmfile diff`
`ACTION=helmfile_sync` runs `helmfile sync`

**Comment by mkj28** [comment]
Not having helmfile here forces Codefresh users to use separate steps/images rather than reuse cfstep-helm

**Comment by jdolitsky** [comment]
@mkj28 this is doable. How do you envision this working with the other options? If `ACTION=helmfile_diff` or `ACTION=helmfile_sync` are specified, just ignore all else?

**Comment by mkj28** [comment]
Maybe? The other option could be just adding helmfile (and helm diff plugin?) to this docker, and then we can simply use the `ACTION=auth` with commands to take it from there....

**Comment by dustinvanbuskirk** [comment]
Closing.

New step incorporating this Docker image: https://github.com/codefresh-contrib/cfstep-helmfile
