### ISSUE TITLE
Add support for --wait

### ISSUE THREAD

**Issue by mkj28** [codefresh-contrib/cfstep-helm#12]
Helm installs should probably wait by default? 

Add both as configurable?
`--wait` if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful. It will wait for as long as --timeout

`--timeout int` time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks) (default 300)

**Comment by davidholsgrove** [comment]
Hi - I too would like to see `--wait` by default (with the option to disable). Can this be added?

**Comment by murbano83** [comment]
👍

**Comment by pasha-codefresh** [comment]
we pushed support for this 
#63
