### ISSUE TITLE
Helm plugins not installed in v3 image

### ISSUE THREAD

**Issue by smithhannahm** [codefresh-contrib/cfstep-helm#25]
The `3.0.0-beta.*` versions are not able to use non-http repositories, as the required plugins are not installed by default. This seems to be because the `.helm` directory has been [deprecated](https://helm.sh/docs/faq/#xdg-base-directory-support) in favor of using the XDG Base Directory specification. Therefore, when the Dockerfile copies files from the `.helm` directory, the plugins aren't there. Instead, they are in the default `$HOME/.local/share` directory.

**Comment by orzarchi** [comment]
Yep, this plugin is now unusable with the default helm repository

**Comment by pasha-codefresh** [comment]
https://github.com/codefresh-contrib/cfstep-helm/commit/933ccc099999b62543efd833d7f7dae9452c99f7

Versions
3.0.3, 3.0.2, 3.0.1 support it now
