### ISSUE TITLE
Tag version 3.2.1 issues

### ISSUE THREAD

**Issue by noamst-monday** [codefresh-contrib/cfstep-helm#91]
Hello!
We are using csftep-helm, locking version to 3.2.1

We are running the following command:
`source /opt/bin/release_chart`

Since the updated tag 2 hours ago ([e6c849ec13d4babe9356cf0d4eb780067ad24c5ddd8fe101e3d4c8ccd6791cc1](https://quay.io/repository/codefreshplugins/cfstep-helm/manifest/sha256:e6c849ec13d4babe9356cf0d4eb780067ad24c5ddd8fe101e3d4c8ccd6791cc1))
This command fails.
What should we do to solve this issue? Can we lock to a specific tag that worked?
Earlier uses of this step with the following sha (7148efbd684468dca1d5b807aaa344da29770463a9d162d815aeeeebf2e951a2)
used to work consistently
![image](https://user-images.githubusercontent.com/99670380/206445075-fd862638-0f30-4b4b-844e-31a85c70c884.png)

Thanks!!

**Comment by pasha-codefresh** [comment]
We have executed revert and now it works
